# .github/workflows/deploy.yml
#
# Correct workflow for a static HTML/JS project (no package.json).
# This version assumes your index.html is in the root of the repository.
#
name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository's files
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Creates the firebaseConfig.js file using your secret
      - name: Create Firebase Config File
        run: |
          # This command now creates the config file in the root directory.
          echo 'export const firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};' > firebaseConfig.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      # 3. Deploys the content of your project folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This now publishes from the root directory.
          publish_dir: ./

